### ISSUE TITLE
Automate deployment

### ISSUE THREAD

**Issue by ryanhiebert** [aldjemy/aldjemy#108]
I have an API token for PyPI that will work for uploading. I just need to get it automated. I'd like it to upload automatically when a new git tag is created.

**Comment by ticosax** [comment]
If you have some pointers for the documentation (according to your preference) I can do the heavy lifting for this one.

**Comment by ticosax** [comment]
Are you fine with this ?
https://github.com/pypa/gh-action-pypi-publish

**Comment by ryanhiebert** [comment]
That looks like a pretty nice way to do it, yeah! We will need to pull things into a single workflow so that we can declare that this will happen after the linting and tests all pass. So lets get all of that working the way we want it, then we'll figure out adding the deployment. I'll be able to get that set up, I've already generated an api token for the purpose.
