### ISSUE TITLE
Async Django and SQLAlchemy

### ISSUE THREAD

**Issue by graingert** [aldjemy/aldjemy#110]
it would be great to have a demo in the docs using the new async sqlalchmy v2 with async django via the asyncpg backend

**Comment by ryanhiebert** [comment]
That sounds really cool, but I honestly don't even know if it's possible yet. Does Django actually support async queries at this point? I wasn't aware of it.

**Comment by graingert** [comment]
@ryanhiebert the django ORM doesn't support async/await but the sqlalchemy 2.0 ORM will do

**Comment by graingert** [comment]
actually it's already in 1.4: https://docs.sqlalchemy.org/en/14/orm/extensions/asyncio.html#sqlalchemy.ext.asyncio.create_async_engine

**Comment by ryanhiebert** [comment]
Thanks for these links, it made for some good reading this morning. I'd love to see an example of this being used, it might help me integrate it into my day job, which would be good for helping me get into this library.

**Comment by ryanhiebert** [comment]
I really like this idea. @graingert are you up for taking a shot at writing these docs? I'd love to know if aldjemy works with async django.

**Comment by graingert** [comment]
I think it might require some modifications to aldjemy, eg use of asyncpg instead of reusing Django connections

**Comment by ryanhiebert** [comment]
That makes sense.
