### ISSUE TITLE
After upgrading to sqlalchemy 1.4.15 tests in my project are failing

### ISSUE THREAD

**Issue by Mogost** [aldjemy/aldjemy#159]
Tests are executed in a transaction. So it looks like there is some problem in the generated schema at the aldjemy level.

https://docs.sqlalchemy.org/en/14/orm/basic_relationships.html#many-to-many

I suspect a problem with many to many relationship in orm.py
Most likely we need to look at the back_populates parameter

```
../../../../../.pyenv/versions/varys/lib/python3.6/site-packages/django/core/management/__init__.py:168: in call_command
    return command.execute(*args, **defaults)
../../../../../.pyenv/versions/varys/lib/python3.6/site-packages/django/core/management/base.py:371: in execute
    output = self.handle(*args, **options)
../management/commands/update_actual_communication_score.py:37: in handle
    recalculate_dense_rank()
../models.py:61: in recalculate_dense_rank
    session.execute(update_query)
../../../../../.pyenv/versions/varys/lib/python3.6/site-packages/sqlalchemy/orm/session.py:1640: in execute
    _parent_execute_state is not None,
../../../../../.pyenv/versions/varys/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py:1821: in orm_pre_session_exec
    update_options,
../../../../../.pyenv/versions/varys/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py:1936: in _do_pre_synchronize_evaluate
    eval_condition = evaluator_compiler.process(*crit)
../../../../../.pyenv/versions/varys/lib/python3.6/site-packages/sqlalchemy/orm/evaluator.py:85: in process
    return meth(clause)
../../../../../.pyenv/versions/varys/lib/python3.6/site-packages/sqlalchemy/orm/evaluator.py:181: in visit_binary
    map(self.process, [clause.left, clause.right])
../../../../../.pyenv/versions/varys/lib/python3.6/site-packages/sqlalchemy/orm/evaluator.py:85: in process
    return meth(clause)
../../../../../.pyenv/versions/varys/lib/python3.6/site-packages/sqlalchemy/orm/evaluator.py:114: in visit_column
    and key in inspect(self.target_cls).column_attrs
../../../../../.pyenv/versions/varys/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py:1164: in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
../../../../../.pyenv/versions/varys/lib/python3.6/site-packages/sqlalchemy/orm/mapper.py:2508: in column_attrs
    return self._filter_properties(properties.ColumnProperty)
../../../../../.pyenv/versions/varys/lib/python3.6/site-packages/sqlalchemy/orm/mapper.py:2557: in _filter_properties
    self._check_configure()
../../../../../.pyenv/versions/varys/lib/python3.6/site-packages/sqlalchemy/orm/mapper.py:1874: in _check_configure
    _configure_registries({self.registry}, cascade=True)
../../../../../.pyenv/versions/varys/lib/python3.6/site-packages/sqlalchemy/orm/mapper.py:3384: in _configure_registries
    _do_configure_registries(registries, cascade)
../../../../../.pyenv/versions/varys/lib/python3.6/site-packages/sqlalchemy/orm/mapper.py:3423: in _do_configure_registries
    mapper._post_configure_properties()
../../../../../.pyenv/versions/varys/lib/python3.6/site-packages/sqlalchemy/orm/mapper.py:1891: in _post_configure_properties
    prop.init()
../../../../../.pyenv/versions/varys/lib/python3.6/site-packages/sqlalchemy/orm/interfaces.py:228: in init
    self.do_init()
../../../../../.pyenv/versions/varys/lib/python3.6/site-packages/sqlalchemy/orm/relationships.py:2141: in do_init
    self._join_condition._warn_for_conflicting_sync_targets()
../../../../../.pyenv/versions/varys/lib/python3.6/site-packages/sqlalchemy/orm/relationships.py:3463: in _warn_for_conflicting_sync_targets
    code="qzyx",
../../../../../.pyenv/versions/varys/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py:1619: in warn
    _warnings_warn(exc.SAWarning(msg, code=code))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

message = SAWarning("relationship 'Group_permissions.group' will copy column auth_group.id to column auth_group_permissions.grou...o isolate the columns that should be written towards.   The 'overlaps' parameter may be used to remove this warning.",)
category = None, stacklevel = 19

    def _warnings_warn(message, category=None, stacklevel=2):
    
        # adjust the given stacklevel to be outside of SQLAlchemy
        try:
            frame = sys._getframe(stacklevel)
        except ValueError:
            # being called from less than 3 (or given) stacklevels, weird,
            # but don't crash
            stacklevel = 0
        except:
            # _getframe() doesn't work, weird interpreter issue, weird,
            # ok, but don't crash
            stacklevel = 0
        else:
            # using __name__ here requires that we have __name__ in the
            # __globals__ of the decorated string functions we make also.
            # we generate this using {"__name__": fn.__module__}
            while frame is not None and re.match(
                r"^(?:sqlalchemy\.|alembic\.)", frame.f_globals.get("__name__", "")
            ):
                frame = frame.f_back
                stacklevel += 1
    
        if category is not None:
            warnings.warn(message, category, stacklevel=stacklevel + 1)
        else:
>           warnings.warn(message, stacklevel=stacklevel + 1)
E           sqlalchemy.exc.SAWarning: relationship 'Group_permissions.group' will copy column auth_group.id to column auth_group_permissions.group_id, which conflicts with relationship(s): 'Group.permissions' (copies auth_group.id to auth_group_permissions.group_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   The 'overlaps' parameter may be used to remove this warning.

../../../../../.pyenv/versions/varys/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py:1660: SAWarning
```

**Comment by ryanhiebert** [comment]
Copying the message with better formatting for this comment thread:

relationship `Group_permissions.group` will copy column `auth_group.id` to column `auth_group_permissions.group_id`, which conflicts with relationship(s): `Group.permissions` (copies `auth_group.id` to `auth_group_permissions.group_id`).

If this is not the intention, consider if these relationships should be linked with `back_populates`, or if `viewonly=True` should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the `orm.foreign()` annotation can be used to isolate the columns that should be written towards.   The `overlaps` parameter may be used to remove this warning.

**Comment by ryanhiebert** [comment]
I *think* what's going on is that many-to-many through tables are creating duplicates over a particular relationship that isn't being specified. `Group_permissions` is a through table, linking `Group` and `Permission`. This happen through `Group.permissions` (which has a back-reference for `Permission.group_set`), but it *also* has individual foreign keys for `Group_permission.group` and `Group_permission.permission`.

So I think that this is a case of *overlapping* relationships, and those relationships need to be able to cooperate.  If that's right, it means that we need to add `overlaps` to these relationships. The challenge with that is if we need to have `overlaps` on more than just the many-to-many, we might not have everything we need when we're constructing each of the relationships.

**Comment by ryanhiebert** [comment]
I tried to update just the ManyToMany through table side with `overlaps`, but unfortunately that didn't fix the issue. Bummer. All the other options are more annoying in different ways. Here they are:

1. Update both of the ManyToMany relationship (the through table as well well as the "concrete" side of the ManyToMany relationship) with `overlaps`.
2. Make the relevant foreign keys of the through table read-only.
3. Make the many-to-many relationship read-only.

3 is by far the easiest option. However, it seems fairly likely that this many-to-many feature is being used by consumers of this library.

2 is more annoying than 3, but it is significantly less likely that those fields are being used by consumers of this library. However, it is still a backward-incompatible change.

1 includes all the annoying work from 2, while retaining backward compatibility. Unfortunately, it's not actually clear that this is the best choice. SQLAlchemy, in version 1.4, started warning when there are overlapping relationships, and it did so for good reason.

In any case we need to add a note to the release notes and the documentation explaining how we decided to square this inconsistency. I'm not sure what the best choice is.

**Comment by ryanhiebert** [comment]
For anyone wanting to get right to the interesting part of the code, this is it, especially lines 90-92 which specify the relationship we make for the many-to-many field:

https://github.com/aldjemy/aldjemy/blob/c2abcb8ceb02fb7d8c3f9d2e133633b6ba6afa46/aldjemy/orm.py#L77-L105

**Comment by ryanhiebert** [comment]
I'm working on solving this. I've asked for some guidance on the SQLAlchemy mailing list on how to best model many-to-many fields.

@Mogost : are you sure that this is causing test failures for you, though? I see these warnings at work, but they aren't causing test failures for me.

**Comment by ryanhiebert** [comment]
Make Bayer on the SQLAlchemy mailing list seemed to think that it might be fairly acceptable to keep backward compatibility, so I'm inclined to do so if I can find a reasonable way to write the code, at least until someone finds the decision obtuse and confusing.

**Comment by ryanhiebert** [comment]
@Mogost : are you raising warnings in your project or something? I've got a local branch that cleans up some warnings, but it's still got some more warnings that aren't cleaned up yet. I hopeful that the warnings you brought up are among them.

**Comment by Mogost** [comment]
I tried #160, the errors are gone.
