### ISSUE TITLE
Settings import conflict in aldjemy.table

### ISSUE THREAD

**Issue by ryanhiebert** [aldjemy/aldjemy#167]
A bug report for 2.0 from @blueyed on #160:

> Note that this broke our settings using django-configurations, because importing `aldjemy.table` requires settings to be configured, while it was not necessary with importing `aldjemy.types`.
`django.core.exceptions.ImproperlyConfigured` gets triggered via https://github.com/aldjemy/aldjemy/blob/aff2d2409fd824f499a5feacc7f2023e646f645f/aldjemy/table.py#L74.
> There's a workaround for this (using django-configurations `setup` method to delay it), but thought you wanted to know, and I also think it might be worth fixing/improving - so feel free to create an issue from this comment.

This certainly strikes me as a bug to fix, as it seems reasonable that someone might want to override with `simple` or `varchar` in their settings, and probably already are. For `simple` it might be trivial enough to just write a lambda. For `varchar` there's a bit more being done, but a lambda probably isn't too bad there either. `foreignkey`, on the other hand, is not complex, but isn't trivial either, and shouldn't have to be recreated.

In most cases, I think we'd really like to be able to have the conversions built-in to Aldjemy if possible, but there are going to be cases where we can't do that. I'd be interested to hear what custom overrides people require to get Aldjemy working. For my case, #166 would make the setting unnecessary for my use-case.

The way I'm inclined to patch it for 2.0, rather than reversing the backward-incompatible change, is to not read the settings from this module, and bring it to the calling location. I'll see if that works out.

**Comment by blueyed** [comment]
Thanks for looking into this!

Yeah, something along the following fixes it:
```diff
diff --git i/aldjemy/table.py w/aldjemy/table.py
index bc7894e..3421b52 100644
--- i/aldjemy/table.py
+++ w/aldjemy/table.py
@@ -70,11 +70,10 @@ def array_type(field):
 }


-# Update with user specified data types
-DATA_TYPES.update(getattr(settings, "ALDJEMY_DATA_TYPES", {}))
-
-
 def generate_tables(metadata):
+    # Update with user specified data types
+    DATA_TYPES.update(getattr(settings, "ALDJEMY_DATA_TYPES", {}))
+
     models = apps.get_models(include_auto_created=True)
     for model in models:
         name = model._meta.db_table
```

(Should use a lowercase name then maybe, and should have a regression test then likely)

**Comment by ryanhiebert** [comment]
`generate_tables` can actually run many times, so I don't think we want to be re-updating `DATA_TYPES`, but that's very similar to what I came up with. It works because it's not accessing settings on module import, giving the settings time to settle first.

Are you willing to review #168? Want to be a part of the Aldjemy team?
