### ISSUE TITLE
Transaction is rollback unconditionally on connection `connect` event

### ISSUE THREAD

**Issue by ticosax** [aldjemy/aldjemy#173]
https://github.com/sqlalchemy/sqlalchemy/commit/37414a752b0036334d0f31ac8cd3aff749c3898b

More specifically this part.
https://github.com/sqlalchemy/sqlalchemy/commit/37414a752b0036334d0f31ac8cd3aff749c3898b#diff-84afdae8b2fe8ee08ff10f4653744adb40b7520ba241bc816d33efcae3df05c0L672-R683
The rollback is emtited from there.

I believe this is undesirable since we would like to let Django deal with the transaction.

Similar to https://github.com/aldjemy/aldjemy/commit/c08ab7b682f3216c9c9be71b6432bfceae9c0040

Apparently the event handler was always there, I'm still investigating why SQLA 1.4 / aldjemy 2 triggers it now and not before.

**Comment by ryanhiebert** [comment]
I don't know why this would have changed, but I certainly do want it to be fixed and working correctly for users. I'm not an active user of SQLAlchemy's transactions in Django requests. For my own use-cases, I construct the query, the get the statement and the parameters after they are compiled and run them as a raw query. However, I'd definitely like this to be fixed, and would be happy to review a pull request and keep the library passing any tests added when this is fixed.

**Comment by ticosax** [comment]
Prior to `1.4` the signal handler was registered with `first_connect` instead of `connect`

https://github.com/sqlalchemy/sqlalchemy/blob/rel_1_3/lib/sqlalchemy/engine/strategies.py#L194

So my understanding, is that aldjemy is interested into triggering what was registered as `connect` only https://github.com/sqlalchemy/sqlalchemy/blob/rel_1_3/lib/sqlalchemy/engine/strategies.py#L192 and not `first_connect`, which has been combined in `1.4`.

Now that we have an understanding of the regression, I will try to find a way to bring back compatibility.

**Comment by ryanhiebert** [comment]
Thank you for your investigation!
