### ISSUE TITLE
option to pass future=True to engine and session

### ISSUE THREAD

**Issue by graingert** [aldjemy/aldjemy#181]
eg https://docs.sqlalchemy.org/en/14/changelog/migration_20.html#migration-to-2-0-step-four-use-the-future-flag-on-session

eg here: https://github.com/aldjemy/aldjemy/blob/e52f05d65d78c24c10c704217dc749986111e82f/aldjemy/orm.py#L16-L17

**Comment by ryanhiebert** [comment]
That makes sense to me. I'm not sure what the API should be for that. Would you like to give it a go?

**Comment by graingert** [comment]
I think maybe a Django settings settings?

Eg:

```
# settings.py
ALDJEMY_ENGINE_FUTURE = True
ALDJEMY_SESSION_FUTURE = True
```

**Comment by ryanhiebert** [comment]
hmm. I don't think I'm a fan of that. Too many settings that are too specific. How about something like a top level `ALDJEMY` settings dict, with defaults for sub-keys `engine_kwargs` and `session_kwargs`? Existing settings might eventually be moved into that top-level dict, but I'd leave that for another round.

**Comment by graingert** [comment]
Well these settings won't be needed for very long. Once sqlalchemy 2 comes out I can upgrade and delete the settings

**Comment by ryanhiebert** [comment]
Is there a use-case for making them different? Should they be just one setting, like `ALDJEMY_SQLALCHEMY_FUTURE`?

**Comment by graingert** [comment]
I don't fully understand why it's in two places

**Comment by ryanhiebert** [comment]
OK. I'd say make it one setting, then, until someone comes up with a use-case for two settings. Thanks for bringing it up. Do you think you can make a pull request? I'd recommend reading the setting in `orm.BaseSQLAModel.query`, which would require modifying the `get_session` function to take that as some kind of a parameter.

**Comment by graingert** [comment]
@zzzeek why are these two options?

**Comment by graingert** [comment]
I can't set the setting in `orm.BaseSQLAModel.query` because Session.query is a legacy method.

I'd only be using `get_session().execute(sa.select(Model.sa))`

**Comment by zzzeek** [comment]
the engine and ORM future mode settings are independent of each other so that people can incrementally upgrade their applications to the newer behaviors.
