### ISSUE TITLE
Inconsistency with json serialization

### ISSUE THREAD

**Issue by holtgrewe** [aldjemy/aldjemy#190]
First of all, thank you very much for aldjemy as it's very helpful for us.

I have found an inconsitency when using aldjemy results vs. Django models results.

Look at the patch here:

https://github.com/holtgrewe/aldjemy/commit/cae18f67810d61042d15ffe7107ef90871f5da34

**Comment by ryanhiebert** [comment]
Thank you for the report. What should I expect to see when those run, and what actually happens? Do you have a suggestion on what might need to be done in order to resolve it?

**Comment by holtgrewe** [comment]
Sorry, I had a second part of the message typed up but it disappeared. I'll need a bit until I can reproduce it again.

**Comment by ryanhiebert** [comment]
No problem, thank you!

**Comment by holtgrewe** [comment]
This went faster than expected. The test complains with

```
======================================================================
FAIL: test_query_sa (sample.tests.TestJsonField)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/holtgrem_c/Development/aldjemy/test_project_postgres/sample/tests.py", line 113, in test_query_sa
    self.assertEquals(obj.value, {"key": "value"})
AssertionError: '{"key": "value"}' != {'key': 'value'}

----------------------------------------------------------------------
Ran 8 tests in 0.952s
```

So it looks like the JSON values are not translated back. The interesting part is that Django from version 2 or 3 expects JsonField/JSONB fields to return strings and translates them into Python objects using `json.loads` automatically. If the underlying connection would be to return already serialized values then the code crashes as a `TypeError` is thrown by `json.loads` instead of an exception from package `json`.

Uhm, does that make my problem clear?

**Comment by ryanhiebert** [comment]
It sounds like we're probably not using the right field type for that field from the Aldjemy side. At this line, we configure that we want to use SQLAlchemy `JSONB` as the type for `JSONField`. Do you think that's correct, or does the mapping need to be something else?

**Comment by ryanhiebert** [comment]
Forgot to post the link to the line: https://github.com/aldjemy/aldjemy/blob/main/aldjemy/table.py#L69

**Comment by holtgrewe** [comment]
I have to say that I'm not such an expert with SQLAlchemy.

Curiously, the patch below fixes the test.

```diff
diff --git a/aldjemy/core.py b/aldjemy/core.py
index 4f9273a..2307295 100644
--- a/aldjemy/core.py
+++ b/aldjemy/core.py
@@ -1,3 +1,5 @@
+import json
+
 import functools
 import time
 from collections import deque
@@ -52,7 +54,7 @@ def get_engine(alias="default", **kwargs):
 
         pool = DjangoPool(alias=alias, creator=None)
         Cache.engines[alias] = create_engine(
-            get_connection_string(alias), pool=pool, **kwargs
+            get_connection_string(alias), pool=pool, json_deserializer=json.loads, **kwargs
         )
     return Cache.engines[alias]
 
```

**Comment by holtgrewe** [comment]
However, I'm doing something similar in a "real" app of mine and this somehow causes the deserializer to be pushed into the psycopg2 driver, apparently, and then Django crashes like this:

```
  File "/opt/miniconda3/envs/varfish-server/lib/python3.7/site-packages/django/db/models/query.py", line 674, in first
    for obj in (self if self.ordered else self.order_by('pk'))[:1]:
  File "/opt/miniconda3/envs/varfish-server/lib/python3.7/site-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/opt/miniconda3/envs/varfish-server/lib/python3.7/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/miniconda3/envs/varfish-server/lib/python3.7/site-packages/django/db/models/query.py", line 68, in __iter__
    for row in compiler.results_iter(results):
  File "/opt/miniconda3/envs/varfish-server/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1122, in apply_converters
    value = converter(value, expression, connection)
  File "/opt/miniconda3/envs/varfish-server/lib/python3.7/site-packages/django/db/models/fields/json.py", line 83, in from_db_value
    return json.loads(value, cls=self.decoder)
  File "/opt/miniconda3/envs/varfish-server/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
```

**Comment by holtgrewe** [comment]
OK, I just pushed this additional patch to the branch.

```diff
diff --git a/test_project_postgres/sample/tests.py b/test_project_postgres/sample/tests.py
index 5b1abd9..635b4f2 100644
--- a/test_project_postgres/sample/tests.py
+++ b/test_project_postgres/sample/tests.py
@@ -113,6 +113,21 @@ class TestJsonField(TestCase):
         self.assertEquals(obj.value, {"key": "value"})
 
 
+    def test_query_both(self):
+        stor = JsonModel(value={"key": "value"})
+        stor.save()
+
+        query = select([JsonModel.sa.id, JsonModel.sa.value])
+        with get_engine().begin() as connection:
+            test_data = connection.execute(query)
+
+        obj = list(test_data)[0]
+        self.assertEquals(obj.value, {"key": "value"})
+
+        obj = JsonModel.objects.get(id=stor.id)
+        self.assertEquals(obj.value, {"key": "value"})
+
+
```

This now causes the following error trace in the tests:

```
======================================================================
ERROR: test_query_both (sample.tests.TestJsonField)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/holtgrem_c/Development/aldjemy/test_project_postgres/sample/tests.py", line 127, in test_query_both
    obj = JsonModel.objects.get(id=stor.id)
  File "/opt/miniconda3/envs/aldjemy-dev/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/miniconda3/envs/aldjemy-dev/lib/python3.7/site-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/opt/miniconda3/envs/aldjemy-dev/lib/python3.7/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/opt/miniconda3/envs/aldjemy-dev/lib/python3.7/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/miniconda3/envs/aldjemy-dev/lib/python3.7/site-packages/django/db/models/query.py", line 68, in __iter__
    for row in compiler.results_iter(results):
  File "/opt/miniconda3/envs/aldjemy-dev/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1122, in apply_converters
    value = converter(value, expression, connection)
  File "/opt/miniconda3/envs/aldjemy-dev/lib/python3.7/site-packages/django/db/models/fields/json.py", line 83, in from_db_value
    return json.loads(value, cls=self.decoder)
  File "/opt/miniconda3/envs/aldjemy-dev/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict

======================================================================
ERROR: test_query_django (sample.tests.TestJsonField)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/holtgrem_c/Development/aldjemy/test_project_postgres/sample/tests.py", line 101, in test_query_django
    obj = JsonModel.objects.get(id=stor.id)
  File "/opt/miniconda3/envs/aldjemy-dev/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/miniconda3/envs/aldjemy-dev/lib/python3.7/site-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/opt/miniconda3/envs/aldjemy-dev/lib/python3.7/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/opt/miniconda3/envs/aldjemy-dev/lib/python3.7/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/miniconda3/envs/aldjemy-dev/lib/python3.7/site-packages/django/db/models/query.py", line 68, in __iter__
    for row in compiler.results_iter(results):
  File "/opt/miniconda3/envs/aldjemy-dev/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1122, in apply_converters
    value = converter(value, expression, connection)
  File "/opt/miniconda3/envs/aldjemy-dev/lib/python3.7/site-packages/django/db/models/fields/json.py", line 83, in from_db_value
    return json.loads(value, cls=self.decoder)
  File "/opt/miniconda3/envs/aldjemy-dev/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict

----------------------------------------------------------------------
Ran 9 tests in 0.692s

FAILED (errors=2)
```

I don't know whether this can be resolved at all without touching Django or SQLAlchemy. :scream: At least I could reproduce it. :clown_face:

**Comment by holtgrewe** [comment]
Sorry for spamming. Regarding your question, I think that aldjemy is using the correct type.

**Comment by holtgrewe** [comment]
@ryanhiebert really, wontfix :scream: ;-)

**Comment by ryanhiebert** [comment]
I need to apologize for two things. First, that I initially viewed your comment as a bit hostile, when in all likelihood it was mean in sarcastic jest. Second, for failing to communicate my thoughts on what you have found, to be clear about what I am able to do, and what I need help with.

As a maintainer I have a responsibility regarding this package. Sometimes people believe that a maintainer's job is to fix the bugs, but the responsibility really is making sure that the community is able to contribute back in a meaningful way. It may have been wise for me to follow up after your work to say that I had heard and understood it, but that I still need further assistance in order to resolve the issue. I didn't recognize the need to respond, but I have followed the work you've done on this issue, and I thank you for the work you've put into it.

I am very happy to see this report and assist in resolving this. When there is a course of action to take, I'm ready to review and merge a pull request, and possibly implement the solution. At this point, I haven't figured out what the right solution is.

> However, I'm doing something similar in a "real" app of mine and this somehow causes the deserializer to be pushed into the psycopg2 driver, apparently, and then Django crashes like this: [crash log omitted]

> I don't know whether this can be resolved at all without touching Django or SQLAlchemy. 😱 At least I could reproduce it. 🤡

Thank you for testing out your suggestion, and letting us know that it isn't as simple as we might have hoped. I recognize that it is likely you've already done the easy work that I know that I can reasonably take the time to do, and it seems that the remaining work is entirely unknown in difficult or time-cost. That's the nature of difficult problems, unfortunately.

I'd very much appreciate assistance in figuring out how best to solve this problem. People might be inclined to over-estimate my knowledge of SQLAlchemy. I recognize its power, and use it when I have a purpose, but this package is a bridge to getting to that power more easily for me, and I maintain the project because it has been helpful to me, not because I'm an expert in SQLAlchemy.

**Comment by holtgrewe** [comment]
Hi @ryanhiebert. Sorry if I did not strike the right tone, I realize that things get lost over the internet in particular when we don't know each other in person. Also, I was not aware of your role and knowledge of the library. I am thankful that you put time into maintaining this and in particular to your long answer here. Please take this as an apology for my lack in better/professional communication.

I will put this on my list of TODOs and dive in more deeply once I can allocate two or three days of my time for it.

**Comment by ryanhiebert** [comment]
Thank you so much, that would be excellent! I would really like to see this issue resolved, and I'm impressed with what you've been able to find already.

**Comment by ashkop** [comment]
Hi! I've also encountered this issue after Django upgrade. What I discovered is that it is cause by this line in Django: https://github.com/django/django/blob/98c8bf1ceeab5c68751c83555f82cff1a9120a67/django/db/backends/postgresql/base.py#L218. And to overcome the issue I just added this event handler:

```
@event.listens_for(Engine, "before_cursor_execute")
def receive_before_cursor_execute(conn, cursor, statement, parameters, context, executemany):
    if isinstance(cursor, Wrapper):
        cursor = cursor.obj
    register_default_jsonb(cursor, loads=json.loads)
```
I didn't want to add `json_deserializer` to the `create_engine` cause it calls `register_default_jsonb` as well, which might affect Django ORM (though I didn't test it myself). In the `before_cursor_execute` handler we can make sure that deserializer is set only for the scope of the current cursor.

**Comment by ryanhiebert** [comment]
Thank you for that investigation, @ashkop. @holtgrewe are you able to see if that seems like a good solution?

**Comment by holtgrewe** [comment]
@ashkop good catch!

@ryanhiebert this looks like a good solution to me. Would we add this event handler to aldjemy as well? Maybe something that can be switched on/off with an environment variable?

**Comment by ryanhiebert** [comment]
I'm open to suggestions, I'm not sure what the right strategy is. I really hesitate to add settings if we can avoid it, but we want Aldjemy to work, preferably by default without configuration.

What do you think the optimal choice is? Is there a change that we would want Django or SQLAlchemy to make? Or is this really something that rightly belongs to Aldjemy to solve?
