### ISSUE TITLE
Replace current Django connection by the new, asynchronous, directly created from the SQLAlchemy

### ISSUE THREAD

**Issue by nnseva** [aldjemy/aldjemy#272]
It would be good to see an option to replace a current Django connection with the new, created from the SQLAlchemy directly, to have availability to use asynchronous SQLAlchemy features.

Such a replacement allows using Aljemy with asynchronous Django views in the most natural manner and makes migration to the full-featured asynchronous Django/Aldjemy application the most smoothly.

Related to #110

**Comment by ryanhiebert** [comment]
I'd love to see that. I haven't had opportunity to get into asynchronous querying yet. Would you be interested in working on it?

**Comment by nnseva** [comment]
mmm ... probably, not yet sure...

**Comment by ticosax** [comment]
I hate to be the party breaker, but one of the advantages of SQLAlchemy is that it re-uses the connection established by django.
It means we can re-use the connection (scarce resource) and the current transaction that is still controlled by django (data integrity).
By switching to another driver we break these assumptions and I see this proposal as maybe too disruptive.
What do you think ? Can we support async without loosing these aspects (same connection/same transaction) ?

**Comment by nnseva** [comment]
@ticosax The asynchronous connection should be implemented using a different PG client library [asyncpg](https://github.com/MagicStack/asyncpg). It means that we can not share connections between Django and SQLAlchemy in this case.

It is a reason why we need to replace a connection with the new one. The old is synchronous, while the new is asynchronous.
This is a reason why I would like to see this feature optional. If somebody relies on the connection sharing option, he/she just doesn't use asynchronous replacement. As opposite, if somebody would like to use SQLAlchemy asynchronous IO he/she will activate an asynchronous replacement option.

Unfortunately, I don't have enough time to implement the feature yet. Maybe somebody else would implement the option, or I could find a time a little bit late.

**Comment by ryanhiebert** [comment]
My knowledge is _waaay_ out of date, but the last I understood the plan was to keep using the synchronous driver in a thread pool.

**Comment by ticosax** [comment]
> My knowledge is _waaay_ out of date, but the last I understood the plan was to keep using the synchronous driver in a thread pool, and have a bridge to access it using async/await.

This could work, assuming django maintain its own connection pool in separate threads and make them available to us.
Could be ? since 4.1 supports async orm operations at python layer (only).
I haven't look too much in depth in the ORM recently (last time was 4 years ago :wink: ).

**Comment by ryanhiebert** [comment]
I'd love to see async stuff happen in this library. It doesn't appear that anyone that has commented thus far is likely to do it, including myself, so I'm going to close this issue, but don't let that stop anyone from getting ambitious. I'd be happy to review it.

@ticosax is correct that we really do want to be using the same connection as Django if at all possible. If we don't do that, I'm not sure that any of Aldjemy's magic is worth much of anything. AFAICT, the models that Aldjemy would still be worthwhile, so the package is still helpful, but that may be all. That said, I have done absolutely no programming against any async Postgres driver, so there's lots of room for me to be wrong.
