### ISSUE TITLE
Is there a way to exclude a Django model or field from Aldjemy model creation?

### ISSUE THREAD

**Issue by christianmlong** [aldjemy/aldjemy#286]
I have a Django model with a field that is a nested Postgres array

```
class MyModel(models.Model):
    array_of_arrays = ArrayField(
        ArrayField(
            models.CharField(max_length=20),
            size=3,
        ),
    )
```

Aldjemy's [array_type](https://github.com/aldjemy/aldjemy/blob/a43758e7d5e4529b9fa504c1603b6590d4ae1d47/aldjemy/table.py#L33-L46) function is throwing `RuntimeError("Unsupported array element type")` for this field.

I don't actually need a SQLAlchemy model for this Django model. Is there a way to exclude a Django model from the Aldjemy model generation process?

**Comment by ryanhiebert** [comment]
I've taken some brief moments refreshing my memory in the code, and I do not currently see a way to skip a model. It certainly makes sense to have that escape hatch somehow. I'm not totally sure how I'd want it to look, but I'd be happy to work with you to see if we can figure out a good solution.

**Comment by christianmlong** [comment]
Thanks! As a starting point, I created a local fork with support for an `ALDJEMY_SKIP_MODELS` setting. If that works out in my use case, I'll send you a PR.

**Comment by ryanhiebert** [comment]
Alternatively, I don't know why the limitation on multi-dimensional arrays exists, and I'd be happy to have that restriction removed if we can test that it works acceptably.
