### ISSUE TITLE
Outdated comment in core.py?

### ISSUE THREAD

**Issue by ElectronicRU** [aldjemy/aldjemy#289]
https://github.com/aldjemy/aldjemy/blob/0e1904ee5bd04892befca00030c84cec07f38346/aldjemy/core.py#L48

autocommit is nowhere in sight, is this a relic of times past?

**Comment by ryanhiebert** [comment]
That comment was introduced in the [initial commit](https://github.com/aldjemy/aldjemy/commit/b75bc873ffb07921be83223429dc6f05aaf08dff), where autocommit was indeed set.

Then [this commit](https://github.com/aldjemy/aldjemy/commit/8584ea900b2446b7c2750135962e4efff320e373) moved the autocommit into the keyword arguments from the function.

Then [this commit](https://github.com/aldjemy/aldjemy/commit/c08ab7b682f3216c9c9be71b6432bfceae9c0040) finally removed that entirely.

So it looks to me that, yes, this is likely an outdated comment.
