### ISSUE TITLE
Scoping SQ sessions to Django requests

### ISSUE THREAD

**Issue by maxnordlund** [aldjemy/aldjemy#52]
I'm not sure if this is the case already, but it would be good as it also would tie the SQ transaction to the request which is what seems logical to me at least.

That would also allow for logging of all SQL queries on errors with some work.

It seems like there's some support in SA for Scoped_sessions to integrate with other libraries, http://docs.sqlalchemy.org/en/rel_1_1/orm/session_basics.html http://docs.sqlalchemy.org/en/rel_1_1/orm/contextual.html#unitofwork-contextual

**Comment by ryanhiebert** [comment]
I'd be interested to know what other libraries that use SQLAlchemy as an ORM do for this. Django uses autocommit mode for requests, and my default is to follow suit, but if the general consensus for Flask-SQLAlchemy, etc, is to do this, I'd be willing to reconsider. I haven't thought through the edge-cases enough to have a strong opinion yet, but I'm willing to entertain pull requests and discussion.

**Comment by maxnordlund** [comment]
I guess following Django here makes the most sense. Flask-SQLAlchemy scopes database sessions to the current application context, which by default is tied to the request. This makes `Model.query` automatically use the current session.

I'm pretty sure they also start with a transaction, so that if you raise an exception in a handler all database modifications are rolled back.

**Comment by ryanhiebert** [comment]
A useful bit of the Django documentation related to this: https://docs.djangoproject.com/en/3.0/topics/db/transactions/#tying-transactions-to-http-requests

**Comment by maxnordlund** [comment]
Taken from the Flask-SQLAlchemy docs:

The only things you need to know compared to plain SQLAlchemy are:

1, SQLAlchemy gives you access to the following things:
  * all the functions and classes from sqlalchemy and sqlalchemy.orm
  * a preconfigured scoped session called session
  * the metadata
  * the engine
  * a SQLAlchemy.create_all() and SQLAlchemy.drop_all() methods to create and drop tables according to the models.
  * a Model baseclass that is a configured declarative base.

2, The Model declarative base class behaves like a regular Python class but has a query attribute attached that can be used to query the model. (Model and BaseQuery)

3, You have to commit the session, but you don’t have to remove it at the end of the request, Flask-SQLAlchemy does that for you.

The last one is most important. It doesn't create an transaction as I thought, but it does tie a session to the request and automatically dispose of it afterwards.
