### ISSUE TITLE
Metadata incorrect for nullable fields

### ISSUE THREAD

**Issue by FalseProtagonist** [aldjemy/aldjemy#57]
The metadata that this library produces for the Django tables has all columns as being nullable, regardless of their specification in their origin classes

It's quite easy fix, just change the generate_tables method to pull the f.null attribute off each element in model.get_fields()

And then pass it into the Column constructor for sqlalchemy with keyword "nullable".

As for motivation, if someone was filthy enough to be wrapping existing django models into sqlalchemy metadata for use in Alembic as part of a migration process, then it might be useful to have this.

It also doesn't pick up indexes (and maybe lots of other things?), but that's a much harder problem to solve since indexes in django normally have horrible anonymous names that I don't know how to reverse engineer

**Comment by ryanhiebert** [comment]
I'm totally on board with matching to the best extent possible the appropriate translation of the Django models. Take them one at a time, and I'd love to see some pull requests for me to review!
