### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by talolard** [aldjemy/aldjemy#67]
Hi
This project looks super useful. Before we dive in, is anyone using this in production  ? Are their any limitations on the SQA side we should be aware of ? 
Thanks

**Comment by ADR-007** [comment]
We use it in production but there are some workarounds like that:
```python
# project/__init__.py

from django.core import signals as core_signals
from django.db import connections

#...

def close_connection(**_):  # fix SqlAlchemy integration
    for conn in connections.all():
        if hasattr(conn, 'sa_session'):
            conn.sa_session.close()


core_signals.request_finished.connect(close_connection)
```

**Comment by ryanhiebert** [comment]
@ADR-007 : Would you like to make a pull request to fix the workarounds? Just help me understand them, and I'll be happy to merge!

**Comment by ADR-007** [comment]
@ryanhiebert , unfortunately, I am not on the project anymore, so I cannot test it...

But the problem was in the open connections which will not be closed automatically  without the hotfix)
