### ISSUE TITLE
Support for virtual fields

### ISSUE THREAD

**Issue by RomanNagornyi** [aldjemy/aldjemy#69]
Hello

Thank you for the library. It is fantastic. Django ORM is trash

One question. Is it possible to support virtual fields from this model translation library https://github.com/zostera/django-modeltrans ? This library support: Translate Django model fields in a PostgreSQL JSONField

I have this model 
```python
class SiteConfiguration(SingletonModel):

    msg = models.CharField(max_length=240,
        blank=True, default='', verbose_name='Help text',
        help_text='Help text {}')
    i18n = TranslationField(fields=("msg",))

    def __str__(self):
        return "Настройки сайта"

    class Meta:
        verbose_name = "Настройки сайта"
        verbose_name_plural = "Настройки сайта"
```

Currently,  columns "msg" for the model isn't visible inside variable metadata.tables when calling _extract_model_attrs function inside apps\aldjemy\orm.py

The problem inside this part 

```python
    for f in model._meta.fields:
        if not isinstance(f, (ForeignKey, OneToOneField)):
            if f.model != model or f.column not in table.c:
                print(tables)
                continue  # Fields from parent model are not supported
            attrs[f.name] = orm.column_property(table.c[f.column])
```

I also added this one

```python
ALDJEMY_DATA_TYPES = {
    'TranslationField':  simple(types.JSON),
}
```

**Comment by ryanhiebert** [comment]
Hmmm. That's a really interesting use-case. I'm interested in us finding a solution, but I'm not terribly equipped to do that myself. It's pretty far outside of what I use this library for ATM. Would you be interested in working on this feature, with my input?
