### ISSUE TITLE
Which Django versions does this support?

### ISSUE THREAD

**Issue by anentropic** [aldjemy/aldjemy#71]
Would be good to note on the README

**Comment by geoffreylzf** [comment]
Can this support django 2.2.3?

**Comment by ryanhiebert** [comment]
I'm using 2.2.3 in production. It works for me.

**Comment by geoffreylzf** [comment]
I keep getting "has no attribute 'sa'" error
I already put aldjemy  as my last in the INSTALLED_APPS list

**Comment by ryanhiebert** [comment]
Without knowing more about your setup, I'm not sure how to debug it. That attribute error seems most likely to happen by not putting `aldjemy` into `INSTALLED_APPS`, though I see that you have confirmed that. Are there any other models that do have the `sa` attribute as expected?

**Comment by cochiseruhulessin** [comment]
Testing on 2.2.6, no errors yet.

**Comment by Mogost** [comment]
It would be great to have exact classifiers here.
https://github.com/Deepwalker/aldjemy/blob/82e1cf59ec697115f11fc9331d6c0c0fc0de0318/setup.py#L24
List of classifiers is [here](https://pypi.org/classifiers/).
