### ISSUE TITLE
Configure custom sqlalchemy custom deserializer

### ISSUE THREAD

**Issue by pradeepbn** [aldjemy/aldjemy#73]
#74 
I'm using postgres array of json elements. The default deserializer in sqlalchemy is expecting serialized JSON. However, the sqlalchemy core is already parsing it to the dict object and hence the default deserializer is failing. Hence, we need the ability to provide custom deserializer to bypass this. 

In the get_engine() api, the custom decode function can passed in through the kwargs passed to the create_engine. Also, the custom deserializer can be used in several occasions where the app developer will require parsing the JSON object to a different structure as per their requirements.

**Comment by ryanhiebert** [comment]
That sounds like a similar global-override case as with #81 , and I suspect that a similar solution would be appropriate: to have a hook at the AppConfig to allow customizing this global behavior.
