### ISSUE TITLE
Maintainers

### ISSUE THREAD

**Issue by ryanhiebert** [aldjemy/aldjemy#79]
Hi @Deepwalker ! @Mogost and I are interested in helping maintain this package. What I'm thinking would be best, if you're amiable to the idea, would be to make a shared organization for the project. I've gone ahead and done that, and I've invited you to be a part of that organization. In return, I'm committing to shepherd the process to get things set up and smoothed out over at that new location, and watch the repository for feedback and issues.

If that sounds like a good approach to you, can you move this repository over to the `aldjemy` organization (so that we can keep the issues that are already here), and give me (ryanhiebert) permissions on the package at PyPI (so that I can make releases)?

If you would prefer not do that, and that is perfectly alright as far as I'm concerned, then @Mogost and I are likely to release a similar package under a different name, but using a shared organization like I've suggested here. We'd rather keep the aldjemy name going if we had our preference, but we understand if you prefer not.

**Comment by Deepwalker** [comment]
Let's create organisation.

**Comment by ryanhiebert** [comment]
Awesome, I see you've accepted the invitation to become an owner there. If you transfer the repository over there, then we will be able to keep the issues, and anyone who has a link will automatically be redirected to the new location.

And can you also add me (ryanhiebert) as an owner over on PyPI, so that I can make releases and such?

**Comment by ryanhiebert** [comment]
@Deepwalker , when you're ready, can you add me (ryanhiebert) as an owner on PyPI, and transfer this repository over to the `aldjemy` organization?

**Comment by Deepwalker** [comment]
How to move it?

**Comment by ryanhiebert** [comment]
Go into the danger zone in the settings. It may have had the org blocked as a destination because of the other repo I had set up there, that should be fixed now.

https://help.github.com/en/github/administering-a-repository/transferring-a-repository

**Comment by ryanhiebert** [comment]
:confetti_ball:
