### ISSUE TITLE
Support for custom Query classes via query_cls and query_class

### ISSUE THREAD

**Issue by thnee** [aldjemy/aldjemy#81]
It would be nice with some built in support for this, to be able to better organize chunks of query parts.

It seems like it has to be specified on both the session, and on relations in models.
https://stackoverflow.com/a/15962062/399725

Flask-sqlalchemy has some nice inspiration too.
https://flask-sqlalchemy.palletsprojects.com/en/2.x/customizing/#query-class

Aldjemy could automate this by reading an `aldjemy_query_class` attribute from the Django model and apply it to the auto generated sa models. It could also traverse relationships during initialization to find out each target model's query class and apply it to relation fields.

What are your thoughts on this? Does it make sense? Did I miss anything obvious?

**Comment by ryanhiebert** [comment]
I don't object, but I don't have a need or a particular use case. However, your suggested implementation won't work, as far as I can tell. The query class needs to be set on the SQLAlchemy database, not just the model. There would need to be some kind of global hook that could take that configuration for _all_ models. Probably something in an `AppConfig`. That would seem like a reasonable way to override global settings for aldjemy.
