### ISSUE TITLE
tests on conda-forge failing with django 2.2

### ISSUE THREAD

**Issue by ltalirz** [aldjemy/aldjemy#90]
The tests for the [aldjemy conda-forge feedstock](https://github.com/conda-forge/aldjemy-feedstock) are currently failing with django 2.2, error message:

    django.db.utils.OperationalError: no such table: django_content_type

[link to build log](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=161813&view=logs&j=1bf226d3-0e2f-52d8-fa93-7d9e633347b3&t=ec8d466d-e3b4-5115-4f06-222398f91e6c&l=754)

For the moment, I limited the django version to <2.2 (as tested also in the CI of this repo), which fixes the tests.

Give that django 3 is already out, this is an important limitation that would be great to either fix or communicate somewhere in the README.

**Comment by ryanhiebert** [comment]
I'm using this project in my Django 3 application, so it does work on Django 3 by some definition, I guess. I certainly need it to be working on Django 3.

**Comment by ltalirz** [comment]
Thanks a lot for the quick reply!
We're also using it together with django 2.2 without issues so far - it may be that the problem pointed out by the test is rather small (I'm not an expert).

A first step could be to simply add django versions 2.2 and 3 to the CI of this repo

**Comment by ryanhiebert** [comment]
Fair enough. I need to get later versions of Python tested under as well. I'm working on a pull request for that. I'm no expert either, just doing my best to maintain this, so if there are failures on that PR, you might well be able to help me solve them.

**Comment by ryanhiebert** [comment]
With #91 merged, is this issue resolved? There's change to the released code, only the tests, is that sufficient?

**Comment by ltalirz** [comment]
Yes, it looks like the breaking change (at least the one caught by the tests) was only in the django test infrastructure.
Thanks @ryanhiebert for the fix!
