### ISSUE TITLE
Parser generator

### ISSUE THREAD

**Issue by Divyashivakumar10** [aldjemy/aldjemy#97]
Hey is this project kind of like sql parser generator?
like it parses the sql query and return an expression and does the code generation from it 

i saw the python syntax, in the readme, how do i execute this project? Do i execute the test.sh file?

**Comment by ryanhiebert** [comment]
Not really. It converts Django models to SQLAlchemy models, so that you can build queries with SQLAlchemy instead of the Django ORM.

**Comment by ryanhiebert** [comment]
You integrate this into a Django project, if you want to use its api. If you want to just run our test suite, you can run `tox`, which in turn runs the `test.sh` script.

**Comment by ryanhiebert** [comment]
Let me know if you have further questions.
